In [1]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("uci breast cancer dataset.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df = df.drop(['Unnamed: 32'], axis=1)

In [4]:
df['diagnosis'] = df['diagnosis'].replace({"M":1, "B":0})

In [5]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df = df.drop(['id'], axis=1)

In [7]:
df1 = df.copy()

In [8]:
x = df.drop(['diagnosis'], axis=1)
y = df[['diagnosis']]

## Chi2 (filter method to select feature)

In [9]:
chi2_selector = SelectKBest(score_func=chi2, k=10)
chi2_selector.fit(x, y)

SelectKBest(score_func=<function chi2 at 0x000001E47FC1D080>)

In [10]:
scores = pd.DataFrame({'Feature':x.columns, "Chi2_score": chi2_selector.scores_})
scores = scores.sort_values(by='Chi2_score', ascending=False)
print(scores)

                    Feature     Chi2_score
23               area_worst  112598.431564
3                 area_mean   53991.655924
13                  area_se    8758.504705
22          perimeter_worst    3665.035416
2            perimeter_mean    2011.102864
20             radius_worst     491.689157
0               radius_mean     266.104917
12             perimeter_se     250.571896
21            texture_worst     174.449400
1              texture_mean      93.897508
26          concavity_worst      39.516915
10                radius_se      34.675247
6            concavity_mean      19.712354
25        compactness_worst      19.314922
27     concave points_worst      13.485419
7       concave points_mean      10.544035
5          compactness_mean       5.403075
28           symmetry_worst       1.298861
16             concavity_se       1.044718
15           compactness_se       0.613785
24         smoothness_worst       0.397366
17        concave points_se       0.305232
8             symmetry_mean       0.257380
29  fractal_dimension_worst       0.231522
4           smoothness_mean       0.149899
11               texture_se       0.009794
19     fractal_dimension_se       0.006371
14            smoothness_se       0.003266
18              symmetry_se       0.000080
9    fractal_dimension_mean       0.000074

In [11]:
selected_feature = x.columns[chi2_selector.get_support()]
print(f'\n Selected Feature:{list(selected_feature)}')

 Selected Feature:['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'perimeter_se', 'area_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst']

In [12]:
df['diagnosis'] = df['diagnosis'].replace({"M":1, "B":1})

# without selecdet feature

In [13]:
X = df.drop(['diagnosis'], axis=1)
Y = df[['diagnosis']]

In [14]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [15]:
log_b = LogisticRegression(max_iter=5000)
log_model_b = log_b.fit(x_train, y_train)
print(f'Train Score:{log_model_b.score(x_train, y_train)}')
print(f'Test Score: {log_model_b.score(x_test, y_test)}')
log_predict_b = log_model_b.predict(x_test)
log_cm_b = confusion_matrix(y_test, log_predict_b)
print(f'confusion_matrix:\n {log_cm_b}')
print(f'accuracy_score: {accuracy_score(y_test, log_predict_b)}')

Train Score:0.9626373626373627
Test Score: 0.956140350877193
confusion_matrix:
 [[70  1]
 [ 4 39]]
accuracy_score: 0.956140350877193

In [16]:
random_b = RandomForestClassifier(n_estimators=100)
random_model_b = random_b.fit(x_train, y_train)
print(f'Train Score:{random_model_b.score(x_train, y_train)}')
print(f'Test Score: {random_model_b.score(x_test, y_test)}')
random_predict_b = random_model_b.predict(x_test)
random_cm_b = confusion_matrix(y_test, random_predict_b)
print(f'confusion_matrix:\n {random_cm_b}')
print(f'accuracy_score: {accuracy_score(y_test, random_predict_b)}')

Train Score:1.0
Test Score: 0.9649122807017544
confusion_matrix:
 [[70  1]
 [ 3 40]]
accuracy_score: 0.9649122807017544

In [17]:
x_new = df[selected_feature]
y = df[['diagnosis']]

In [18]:
xtrain, xtest, ytrain, ytest = train_test_split(x_new, y, test_size=0.2, random_state=42)

# with Selected Feature

In [19]:
log = LogisticRegression(max_iter=5000)
log_model = log.fit(xtrain, ytrain)
print(f'Train Score:{log_model.score(xtrain, ytrain)}')
print(f'Test Score: {log_model.score(xtest, ytest)}')
log_predict = log_model.predict(xtest)
cm = confusion_matrix(ytest, log_predict)
print(f'confusion_matrix:\n {cm}')
print(f'accuracy_score: {accuracy_score(ytest, log_predict)}')

Train Score:0.945054945054945
Test Score: 0.9649122807017544
confusion_matrix:
 [[70  1]
 [ 3 40]]
accuracy_score: 0.9649122807017544

In [20]:
random = RandomForestClassifier(n_estimators=100)
random_model= random.fit(xtrain, ytrain)
print(f'Train Score:{random_model.score(xtrain, ytrain)}')
print(f'Test Score: {random_model.score(xtest, ytest)}')
random_predict = random_model.predict(xtest)
random_cm = confusion_matrix(ytest, random_predict)
print(f'confusion_matrix:\n {random_cm}')
print(f'accuracy_score: {accuracy_score(ytest, random_predict)}')

Train Score:1.0
Test Score: 0.9649122807017544
confusion_matrix:
 [[70  1]
 [ 3 40]]
accuracy_score: 0.9649122807017544

# RFE (Recursive Feature Elimination)
# Wrapper Method to select feature

In [21]:
from sklearn.feature_selection import RFE

In [22]:
a = df1.drop(['diagnosis'], axis=1)
b = df1[['diagnosis']]

In [23]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=42)

In [25]:
log_all = LogisticRegression(max_iter=5000)
model_all = log_all.fit(a_train, b_train)
print(model_all.score(a_train, b_train))
print(model_all.score(a_test, b_test))

0.9626373626373627
0.956140350877193

In [24]:
logistic = LogisticRegression(max_iter=5000)
rfe = RFE(logistic, n_features_to_select=5)
rfe

RFE(estimator=LogisticRegression(max_iter=5000), n_features_to_select=5)

In [26]:
rfe.fit(a_train, b_train)

RFE(estimator=LogisticRegression(max_iter=5000), n_features_to_select=5)

In [32]:
selected_feature = a.columns[rfe.support_]
selected_feature

Index(['radius_mean', 'texture_se', 'radius_worst', 'compactness_worst',
       'concavity_worst'],
      dtype='object')

In [33]:
a_train_selected = a_train[selected_feature]
a_test_selected = a_test[selected_feature]

In [36]:
log_sel = LogisticRegression(max_iter=5000)
model_sel = log_sel.fit(a_train_selected, b_train)
print(model_sel.score(a_train_selected, b_train))
print(model_sel.score(a_test_selected, b_test))
model_sel_pred = model_sel.predict(a_test_selected)
print(f"accuracy_score: {accuracy_score(b_test, model_sel_pred)}")

0.9494505494505494
0.9736842105263158
accuracy_score: 0.9736842105263158